/**
 * Analytics event tracking utilities
 *
 * These functions send events to Google Analytics 4
 * when users interact with key conversion elements.
 */

declare global {
  interface Window {
    gtag?: (
      command: 'event',
      eventName: string,
      eventParams?: Record<string, any>
    ) => void;
  }
}

function trackEvent(eventName: string, eventParams?: Record<string, any>) {
  if (typeof window !== 'undefined' && window.gtag) {
    window.gtag('event', eventName, eventParams);
  }
}

export function serviceCategoryForPath(path: string) {
  const value = path.toLowerCase();

  if (value.includes('electrical-load-studies') || value.includes('load-study')) {
    return 'electrical_load_studies';
  }

  if (value.includes('commercial-electric-vehicle') || value.includes('commercial-ev')) {
    return 'commercial_ev_charging';
  }

  if (value.includes('residential-ev') || value.includes('ev-charger')) {
    return 'residential_ev_charging';
  }

  if (value.includes('panel')) {
    return 'panel_upgrades';
  }

  if (value.includes('led-retrofit') || value.includes('lighting')) {
    return 'led_retrofit';
  }

  if (value.includes('commercial-service')) {
    return 'commercial_electrical';
  }

  return 'general_electrical';
}

/**
 * Track phone number clicks
 */
export function trackPhoneClick(phoneNumber: string, location: string) {
  trackEvent('phone_click', {
    phone_number: phoneNumber,
    location: location,
    service_category: serviceCategoryForPath(location),
    event_category: 'lead',
    event_label: `Phone click from ${location}`,
  });
}

/**
 * Track CTA button clicks
 */
export function trackCTAClick(buttonText: string, buttonLocation: string, destination?: string) {
  trackEvent('cta_click', {
    button_text: buttonText,
    button_location: buttonLocation,
    destination: destination || '',
    service_category: serviceCategoryForPath(buttonLocation),
    event_category: 'engagement',
    event_label: `CTA: ${buttonText}`,
  });
}

/**
 * Track form submissions
 */
export function trackFormSubmit(formName: string, formLocation: string) {
  trackEvent('form_submit', {
    form_name: formName,
    form_location: formLocation,
    service_category: serviceCategoryForPath(formLocation),
    event_category: 'lead',
    event_label: `Form submitted: ${formName}`,
  });
}

/**
 * Track email clicks
 */
export function trackEmailClick(email: string, location: string) {
  trackEvent('email_click', {
    email: email,
    location: location,
    service_category: serviceCategoryForPath(location),
    event_category: 'lead',
    event_label: `Email click from ${location}`,
  });
}

/**
 * Track GA4 recommended lead events.
 */
export function trackGenerateLead(method: string, location: string) {
  trackEvent('generate_lead', {
    method,
    location,
    service_category: serviceCategoryForPath(location),
    event_category: 'lead',
    event_label: `Lead generated by ${method}`,
  });
}

export function trackQualifiedLead(method: string, location: string) {
  trackEvent('qualified_lead', {
    method,
    location,
    service_category: serviceCategoryForPath(location),
    event_category: 'lead',
    event_label: `Qualified lead by ${method}`,
  });
}

/**
 * Track service page views (for conversion funnel analysis)
 */
export function trackServiceView(serviceName: string, location: string) {
  trackEvent('service_view', {
    service_name: serviceName,
    location: location,
    service_category: serviceCategoryForPath(location),
    event_category: 'engagement',
    event_label: `Viewed service: ${serviceName} in ${location}`,
  });
}
