CREATE TABLE IF NOT EXISTS location_local_seo (
  location_slug TEXT PRIMARY KEY,
  utility_name TEXT NOT NULL,
  permit_office TEXT NOT NULL,
  permit_note TEXT NOT NULL,
  property_context TEXT NOT NULL,
  parking_context TEXT NOT NULL,
  commercial_context TEXT NOT NULL,
  FOREIGN KEY (location_slug) REFERENCES location_pages(location_slug)
);

INSERT OR REPLACE INTO location_local_seo (
  location_slug,
  utility_name,
  permit_office,
  permit_note,
  property_context,
  parking_context,
  commercial_context
) VALUES
('altadena', 'Southern California Edison', 'Los Angeles County Building and Safety', 'Projects in Altadena commonly require county permit coordination, utility capacity review, and careful planning for older homes, rebuild work, hillside conditions, and detached parking areas.', 'Altadena includes older single family homes, hillside properties, rebuild sites, accessory structures, and detached garages where panel location, grounding, and service capacity deserve early review.', 'Detached garages, long driveway runs, carports, and rebuild parking layouts can affect EV charger placement, trenching, conduit routing, and voltage drop.', 'Local commercial work is often smaller site service, exterior lighting, dedicated equipment circuits, panel repair, and tenant improvement electrical coordination.'),
('atwater-village', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Atwater Village projects are typically reviewed through Los Angeles city permitting, with LADWP service planning important for EV chargers, panel upgrades, and larger dedicated circuits.', 'Atwater Village has older homes, small multifamily buildings, creative offices, storefronts, and mixed parking conditions that often need panel and load review before new electrical scope.', 'Driveways, detached garages, small multifamily parking, and alley access can shape charger location, conduit path, and inspection planning.', 'Commercial corridors and creative spaces commonly need lighting retrofits, dedicated equipment circuits, troubleshooting, and EV charging planning.'),
('beverly-hills', 'Southern California Edison', 'City of Beverly Hills Community Development', 'Beverly Hills projects often require city specific permit coordination, careful schedule planning, and clean documentation for residential estates, multifamily buildings, retail spaces, and commercial properties.', 'Beverly Hills includes luxury homes, older estates, multifamily buildings, retail storefronts, and office properties where finish protection, panel capacity, and access planning matter.', 'Garages, gated driveways, subterranean parking, and multifamily stalls can affect charger placement, load management, and conduit concealment.', 'Retail, medical, office, hospitality, and service businesses commonly need dedicated equipment circuits, lighting upgrades, panel work, and EV charging feasibility review.'),
('boyle-heights', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Boyle Heights projects are usually handled through Los Angeles city permitting, with LADWP coordination important for service upgrades, EV charging, and commercial electrical work.', 'Boyle Heights includes older homes, multifamily buildings, storefronts, industrial edges, and mixed use properties where existing wiring and panel condition should be checked early.', 'Tight driveways, rear parking, detached structures, and shared parking areas can shape charger routing and equipment placement.', 'Commercial spaces may need panel repairs, dedicated equipment circuits, lighting work, code corrections, and EV charging planning.'),
('burbank', 'Burbank Water and Power', 'City of Burbank Building and Safety', 'Burbank electrical projects often involve municipal utility coordination through Burbank Water and Power and city permit review for service changes, EV chargers, and commercial improvements.', 'Burbank includes single family homes, apartment buildings, studios, offices, warehouses, and retail spaces with varied electrical loads and access conditions.', 'Garages, carports, studio lots, and commercial parking areas can affect charger layout, metering, conduit routing, and load management.', 'Studio, office, retail, and warehouse properties commonly need dedicated circuits, lighting retrofits, panel service, backup power planning, and EV charging infrastructure.'),
('culver-city', 'Southern California Edison', 'City of Culver City Building Safety', 'Culver City projects commonly require city permit coordination and utility capacity review for EV charging, panel upgrades, tenant improvements, and commercial electrical work.', 'Culver City has homes, townhomes, multifamily buildings, creative offices, production spaces, retail corridors, and mixed use properties where electrical capacity planning matters.', 'Garage stalls, multifamily parking, alley access, and commercial parking areas can affect charger routing, load sharing, and inspection planning.', 'Creative offices, studios, restaurants, retail spaces, and commercial buildings often need lighting upgrades, dedicated circuits, troubleshooting, and EV charging feasibility review.'),
('echo-park', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Echo Park projects are typically reviewed through Los Angeles city permitting, with LADWP service planning important for hillside homes, older wiring, multifamily buildings, and EV charger work.', 'Echo Park includes hillside homes, older single family properties, duplexes, multifamily buildings, storefronts, and creative spaces where access and service capacity can drive the electrical plan.', 'Steep lots, street parking, detached garages, carports, and small multifamily parking can affect EV charger placement and conduit routes.', 'Local commercial work often includes storefront lighting, dedicated circuits, panel repairs, troubleshooting, and small tenant improvement electrical scope.'),
('glendale', 'Glendale Water and Power', 'City of Glendale Building and Safety', 'Glendale projects commonly involve municipal utility coordination through Glendale Water and Power and city permit review for EV chargers, service upgrades, panels, and commercial electrical work.', 'Glendale has hillside homes, multifamily properties, retail centers, offices, industrial spaces, and older electrical systems that benefit from load review before added equipment.', 'Garages, multifamily parking, hillside driveways, and commercial lots can affect EV charger placement, conduit routing, and utility planning.', 'Retail, office, medical, warehouse, and multifamily properties commonly need panel work, lighting retrofits, dedicated equipment circuits, and EV charging planning.'),
('highland-park', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Highland Park projects are usually handled through Los Angeles city permitting, with LADWP service review important for older homes, hillside conditions, multifamily buildings, and EV charging work.', 'Highland Park includes older homes, hillside lots, duplexes, small apartments, storefronts, and mixed use properties where panels, grounding, and access often need review.', 'Detached garages, steep driveways, rear parking, and limited off street parking can shape charger location and conduit routing.', 'Local commercial spaces commonly need lighting, dedicated circuits, panel repair, code corrections, and troubleshooting.'),
('hollywood', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Hollywood projects are typically reviewed through Los Angeles city permitting, with LADWP coordination important for commercial electrical work, multifamily properties, EV chargers, and service changes.', 'Hollywood includes apartments, condos, older homes, mixed use buildings, retail spaces, studios, and hospitality properties with varied load profiles and access constraints.', 'Subterranean parking, shared garages, alley access, and limited parking can affect charger placement, load sharing, and equipment routing.', 'Studios, retail, hospitality, offices, restaurants, and multifamily buildings commonly need dedicated circuits, lighting retrofits, panel work, troubleshooting, and EV charging planning.'),
('inglewood', 'Southern California Edison', 'City of Inglewood Building and Safety', 'Inglewood projects commonly require city permit coordination and utility capacity review for EV charging, panel upgrades, commercial buildouts, lighting, and dedicated circuits.', 'Inglewood includes homes, apartments, retail, commercial corridors, hospitality properties, and industrial spaces where load planning and panel condition matter.', 'Driveways, garages, multifamily parking, and commercial lots can affect charger placement, routing, and load management.', 'Local commercial projects often involve lighting upgrades, dedicated equipment circuits, panel service, troubleshooting, tenant improvements, and EV charging feasibility.'),
('long-beach', 'Southern California Edison', 'Long Beach Development Services', 'Long Beach projects commonly require city permit coordination and utility planning for EV charging, panel upgrades, multifamily parking, retail spaces, and commercial electrical work.', 'Long Beach includes coastal homes, apartments, condos, retail corridors, warehouses, offices, and mixed use properties with varied parking and electrical access.', 'Garages, multifamily parking, coastal exterior equipment, commercial lots, and fleet parking can affect charger location, weather exposure, and conduit routing.', 'Retail, hospitality, warehouse, office, multifamily, and port adjacent properties commonly need lighting, dedicated circuits, panel work, and EV charging planning.'),
('los-feliz', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Los Feliz projects are typically reviewed through Los Angeles city permitting, with LADWP coordination important for hillside homes, older wiring, multifamily buildings, and EV charging work.', 'Los Feliz includes hillside homes, older houses, apartment buildings, condos, and local commercial spaces where panel capacity, access, and finish protection matter.', 'Hillside driveways, detached garages, shared parking, and tight access can shape EV charger placement and conduit routes.', 'Local commercial work often includes lighting, dedicated equipment circuits, troubleshooting, panel service, and code corrections.'),
('pacific-palisades', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Pacific Palisades projects are usually reviewed through Los Angeles city permitting, with LADWP service planning important for rebuild work, hillside homes, EV chargers, and larger residential electrical loads.', 'Pacific Palisades includes hillside homes, coastal properties, fire rebuilds, luxury residences, detached garages, and properties with larger electrical equipment loads.', 'Garages, long driveways, hillside routing, exterior equipment exposure, and rebuild parking layouts can affect charger placement and electrical design.', 'Local commercial work is typically retail, service, lighting, dedicated circuits, panel service, and EV charging planning.'),
('pasadena', 'Pasadena Water and Power', 'City of Pasadena Permit Center', 'Pasadena projects commonly involve Pasadena Water and Power coordination and city permit review for EV chargers, service upgrades, panel work, and commercial electrical improvements.', 'Pasadena includes historic homes, multifamily buildings, hillside properties, retail corridors, offices, and fire rebuild contexts where permitting, access, and panel capacity need care.', 'Detached garages, historic homes, multifamily parking, hillside driveways, and rebuild layouts can affect EV charger planning and service capacity.', 'Retail, office, medical, hospitality, multifamily, and institutional properties commonly need panel work, lighting, dedicated circuits, troubleshooting, and EV charging planning.'),
('santa-clarita', 'Southern California Edison', 'City of Santa Clarita Building and Safety', 'Santa Clarita projects commonly require city permit coordination and SCE service planning for EV chargers, panel upgrades, backup power, and commercial electrical work.', 'Santa Clarita includes suburban homes, garages, townhomes, retail centers, warehouses, offices, and larger parking areas where load planning is important.', 'Attached garages, long circuit runs, commercial lots, and fleet parking areas can affect charger placement, voltage drop, and equipment layout.', 'Retail, warehouse, office, and facility properties commonly need lighting upgrades, dedicated equipment circuits, panel service, backup power planning, and EV charging infrastructure.'),
('santa-monica', 'Southern California Edison', 'City of Santa Monica Building and Safety', 'Santa Monica projects commonly require city permit coordination and utility capacity review for EV chargers, multifamily parking, coastal equipment, and commercial electrical upgrades.', 'Santa Monica includes homes, condos, multifamily buildings, retail, hospitality, offices, and coastal properties where exterior equipment, access, and parking conditions matter.', 'Multifamily garages, tandem parking, subterranean parking, coastal exposure, and commercial lots can affect charger placement and load management.', 'Retail, hospitality, office, multifamily, and restaurant properties commonly need lighting, panel work, dedicated circuits, troubleshooting, and EV charging planning.'),
('sherman-oaks', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Sherman Oaks projects are typically reviewed through Los Angeles city permitting, with LADWP coordination important for EV chargers, panel upgrades, hillside homes, and commercial electrical work.', 'Sherman Oaks includes single family homes, hillside properties, apartments, condos, offices, retail spaces, and restaurants with varied electrical loads and parking layouts.', 'Garages, hillside driveways, multifamily parking, and commercial lots can affect EV charger placement, conduit routing, and panel capacity.', 'Ventura Boulevard commercial spaces, offices, restaurants, retail, and multifamily buildings commonly need lighting, dedicated circuits, panel service, and EV charging planning.'),
('silver-lake', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Silver Lake projects are usually reviewed through Los Angeles city permitting, with LADWP coordination important for hillside homes, older panels, multifamily buildings, and EV charging work.', 'Silver Lake includes hillside homes, older houses, duplexes, apartments, creative offices, and retail spaces where access, grounding, and load capacity need review.', 'Steep driveways, detached garages, shared parking, and narrow access can affect EV charger location and conduit routing.', 'Local commercial work commonly includes lighting, dedicated circuits, panel repair, troubleshooting, small tenant improvements, and EV charging feasibility.'),
('torrance', 'Southern California Edison', 'City of Torrance Community Development', 'Torrance projects commonly require city permit coordination and SCE capacity review for EV charging, panel work, industrial electrical loads, and commercial improvements.', 'Torrance includes single family homes, apartments, retail centers, medical offices, warehouses, industrial properties, and larger parking areas where electrical planning matters.', 'Garages, commercial lots, fleet parking, warehouse parking, and multifamily stalls can affect charger placement, load management, and routing.', 'Industrial, retail, medical, office, warehouse, and multifamily properties commonly need dedicated circuits, lighting, panel service, troubleshooting, and EV charging infrastructure.'),
('venice', 'Los Angeles Department of Water and Power', 'Los Angeles Department of Building and Safety', 'Venice projects are typically reviewed through Los Angeles city permitting, with LADWP service review important for coastal homes, multifamily parking, retail spaces, and EV charging work.', 'Venice includes coastal homes, duplexes, multifamily buildings, retail storefronts, restaurants, offices, and properties with tight access or exterior exposure.', 'Carports, narrow lots, alley access, coastal exposure, shared parking, and detached structures can affect charger placement and conduit routing.', 'Retail, restaurant, office, hospitality, and multifamily spaces commonly need lighting, dedicated circuits, panel service, troubleshooting, and EV charging planning.'),
('west-hollywood', 'Southern California Edison', 'City of West Hollywood Building and Safety', 'West Hollywood projects commonly require city permit coordination and utility capacity review for multifamily buildings, retail, hospitality, EV chargers, and commercial electrical work.', 'West Hollywood includes condos, apartments, retail, restaurants, hospitality spaces, offices, and older mixed use buildings where panel capacity and access planning are important.', 'Subterranean parking, shared garages, limited parking, and commercial lots can affect charger placement, load sharing, and routing.', 'Restaurants, retail, hospitality, offices, and multifamily buildings commonly need lighting, dedicated equipment circuits, panel service, troubleshooting, and EV charging planning.');

UPDATE location_pages SET city = 'Altadena', zip_code = '91001', latitude = '34.1897', longitude = '-118.1312' WHERE location_slug = 'altadena';
UPDATE location_pages SET city = 'Los Angeles', zip_code = '90039', latitude = '34.1164', longitude = '-118.2565' WHERE location_slug = 'atwater-village';
UPDATE location_pages SET city = 'Los Angeles', zip_code = '90033', latitude = '34.0339', longitude = '-118.2053' WHERE location_slug = 'boyle-heights';
UPDATE location_pages SET city = 'Los Angeles', zip_code = '90026', latitude = '34.0782', longitude = '-118.2606' WHERE location_slug = 'echo-park';
UPDATE location_pages SET city = 'Los Angeles', zip_code = '90042', latitude = '34.1157', longitude = '-118.1854' WHERE location_slug = 'highland-park';
UPDATE location_pages SET city = 'Inglewood', zip_code = '90301', latitude = '33.9617', longitude = '-118.3531' WHERE location_slug = 'inglewood';
UPDATE location_pages SET city = 'Los Angeles', zip_code = '90027', latitude = '34.1086', longitude = '-118.2870' WHERE location_slug = 'los-feliz';
UPDATE location_pages SET city = 'Santa Clarita', zip_code = '91355', latitude = '34.3917', longitude = '-118.5426' WHERE location_slug = 'santa-clarita';
UPDATE location_pages SET city = 'Los Angeles', zip_code = '91403', latitude = '34.1483', longitude = '-118.4517' WHERE location_slug = 'sherman-oaks';
UPDATE location_pages SET city = 'Los Angeles', zip_code = '90039', latitude = '34.0867', longitude = '-118.2702' WHERE location_slug = 'silver-lake';
